### PR TITLE
Install mlterm without X - relying on Cocoa

### PR DESCRIPTION
**Pull request by lucafavatella**
Please refer to commit message for details.

@saitoha @aki017

### CODE REVIEW

**Comment by lucafavatella** [comment]
I tested the resulting img2sixel on a png and it was shown in the terminal itself (mlterm).

**Comment by saitoha** [comment]
@lucafavatella Thanks, I'll test it tomorrow!

**Comment by saitoha** [comment]
@lucafavatella It works fine!
But my X version mlterm is overritten.
Do you have any idea to preserve it?

**Comment by lucafavatella** [comment]
I am not looking at the code now, but I expect the configure of mlterm to
offer options for building cocoa or x - plus the .app thingy might need to
be conditional only if cocoa. It looks like you would like the formula to
accept options in order to be built with either cocoa or x, right? (The
same formula cannot be installed at the same time with two distinct set of
options.)
On 12 Apr 2016 18:31, "Hayaki Saito" notifications@github.com wrote:

@lucafavatella https://github.com/lucafavatella It works fine!
But my X version mlterm is overritten.
Do you have any idea to preserve it?

**Comment by saitoha** [comment]
@lucafavatella OK, I just understand that both Cocoa and X versoin cannot co-exist.
Can you add an option to this patch to built with X11?

**Comment by lucafavatella** [comment]
I will try to put a patch together these days.

**Comment by saitoha** [comment]
OK, Now I merge it into master. Tell me when your additional patch is ready.

**Pull request merged**
